// Code generated by "stringer -type DragResult"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DRAG_RESULT_SUCCESS-0]
	_ = x[DRAG_RESULT_NO_TARGET-1]
	_ = x[DRAG_RESULT_USER_CANCELLED-2]
	_ = x[DRAG_RESULT_TIMEOUT_EXPIRED-3]
	_ = x[DRAG_RESULT_GRAB_BROKEN-4]
	_ = x[DRAG_RESULT_ERROR-5]
}

const _DragResult_name = "DRAG_RESULT_SUCCESSDRAG_RESULT_NO_TARGETDRAG_RESULT_USER_CANCELLEDDRAG_RESULT_TIMEOUT_EXPIREDDRAG_RESULT_GRAB_BROKENDRAG_RESULT_ERROR"

var _DragResult_index = [...]uint8{0, 19, 40, 66, 93, 116, 133}

func (i DragResult) String() string {
	if i >= DragResult(len(_DragResult_index)-1) {
		return "DragResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DragResult_name[_DragResult_index[i]:_DragResult_index[i+1]]
}
