// Code generated by "stringer -type EventFlag"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EVENT_PASS-0]
	_ = x[EVENT_STOP-1]
}

const _EventFlag_name = "EVENT_PASSEVENT_STOP"

var _EventFlag_index = [...]uint8{0, 10, 20}

func (i EventFlag) String() string {
	if i < 0 || i >= EventFlag(len(_EventFlag_index)-1) {
		return "EventFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventFlag_name[_EventFlag_index[i]:_EventFlag_index[i+1]]
}
