// Code generated by "stringer -type HorizontalAlignment"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ALIGN_LEFT-0]
	_ = x[ALIGN_RIGHT-1]
	_ = x[ALIGN_CENTER-2]
}

const _HorizontalAlignment_name = "ALIGN_LEFTALIGN_RIGHTALIGN_CENTER"

var _HorizontalAlignment_index = [...]uint8{0, 10, 21, 33}

func (i HorizontalAlignment) String() string {
	if i >= HorizontalAlignment(len(_HorizontalAlignment_index)-1) {
		return "HorizontalAlignment(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HorizontalAlignment_name[_HorizontalAlignment_index[i]:_HorizontalAlignment_index[i+1]]
}
