// Code generated by "stringer -type Justification"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[JUSTIFY_LEFT-0]
	_ = x[JUSTIFY_RIGHT-1]
	_ = x[JUSTIFY_CENTER-2]
	_ = x[JUSTIFY_FILL-3]
}

const _Justification_name = "JUSTIFY_LEFTJUSTIFY_RIGHTJUSTIFY_CENTERJUSTIFY_FILL"

var _Justification_index = [...]uint8{0, 12, 25, 39, 51}

func (i Justification) String() string {
	if i >= Justification(len(_Justification_index)-1) {
		return "Justification(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Justification_name[_Justification_index[i]:_Justification_index[i+1]]
}
