// Code generated by "stringer -type Orientation"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ORIENTATION_NONE-0]
	_ = x[ORIENTATION_HORIZONTAL-1]
	_ = x[ORIENTATION_VERTICAL-2]
}

const _Orientation_name = "ORIENTATION_NONEORIENTATION_HORIZONTALORIENTATION_VERTICAL"

var _Orientation_index = [...]uint8{0, 16, 38, 58}

func (i Orientation) String() string {
	if i >= Orientation(len(_Orientation_index)-1) {
		return "Orientation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Orientation_name[_Orientation_index[i]:_Orientation_index[i+1]]
}
