// Code generated by "stringer -type VerticalAlignment"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ALIGN_TOP-0]
	_ = x[ALIGN_BOTTOM-1]
	_ = x[ALIGN_MIDDLE-2]
}

const _VerticalAlignment_name = "ALIGN_TOPALIGN_BOTTOMALIGN_MIDDLE"

var _VerticalAlignment_index = [...]uint8{0, 9, 21, 33}

func (i VerticalAlignment) String() string {
	if i >= VerticalAlignment(len(_VerticalAlignment_index)-1) {
		return "VerticalAlignment(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VerticalAlignment_name[_VerticalAlignment_index[i]:_VerticalAlignment_index[i+1]]
}
