// Code generated by "stringer -type WindowType"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WINDOW_TOPLEVEL-0]
	_ = x[WINDOW_POPUP-1]
}

const _WindowType_name = "WINDOW_TOPLEVELWINDOW_POPUP"

var _WindowType_index = [...]uint8{0, 15, 27}

func (i WindowType) String() string {
	if i >= WindowType(len(_WindowType_index)-1) {
		return "WindowType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WindowType_name[_WindowType_index[i]:_WindowType_index[i+1]]
}
