// Code generated by "stringer -type WrapMode"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WRAP_NONE-0]
	_ = x[WRAP_CHAR-1]
	_ = x[WRAP_WORD-2]
	_ = x[WRAP_WORD_CHAR-3]
}

const _WrapMode_name = "WRAP_NONEWRAP_CHARWRAP_WORDWRAP_WORD_CHAR"

var _WrapMode_index = [...]uint8{0, 9, 18, 27, 41}

func (i WrapMode) String() string {
	if i >= WrapMode(len(_WrapMode_index)-1) {
		return "WrapMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WrapMode_name[_WrapMode_index[i]:_WrapMode_index[i+1]]
}
